<?php

include_once('objective_planning.features.inc');

/**
 * Implementation of hook_init().
 */
function objective_planning_init() {
  drupal_add_css('/itdev/sites/all/themes/fusion/fusion_core/css/grid16-fluid.css');
  drupal_add_css(drupal_get_path('module', 'objective_planning') .'/css/objective_planning.css');
  //drupal_add_js(drupal_get_path('module', 'objective_planning') .'/js/objective_planning.js');
 }
